"""Smoke tests for backend/api/voting/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_voting_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.voting.router")
    assert mod is not None

def test_vote_useful_is_callable():
    """Function vote_useful exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.voting.router")
    fn = getattr(mod, "vote_useful", None)
    assert fn is not None, "'vote_useful' not found in backend.api.voting.router"
    assert callable(fn)

def test_remove_vote_is_callable():
    """Function remove_vote exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.voting.router")
    fn = getattr(mod, "remove_vote", None)
    assert fn is not None, "'remove_vote' not found in backend.api.voting.router"
    assert callable(fn)
