"""Smoke tests for backend/api/auth/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_auth_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    assert mod is not None

def test_create_jwt_is_callable():
    """Function create_jwt exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "create_jwt", None)
    assert fn is not None, "'create_jwt' not found in backend.api.auth.router"
    assert callable(fn)

def test_decode_jwt_is_callable():
    """Function decode_jwt exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "decode_jwt", None)
    assert fn is not None, "'decode_jwt' not found in backend.api.auth.router"
    assert callable(fn)

def test_get_current_user_is_callable():
    """Function get_current_user exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "get_current_user", None)
    assert fn is not None, "'get_current_user' not found in backend.api.auth.router"
    assert callable(fn)

def test_login_is_callable():
    """Function login exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "login", None)
    assert fn is not None, "'login' not found in backend.api.auth.router"
    assert callable(fn)

def test_callback_is_callable():
    """Function callback exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "callback", None)
    assert fn is not None, "'callback' not found in backend.api.auth.router"
    assert callable(fn)

def test_logout_is_callable():
    """Function logout exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "logout", None)
    assert fn is not None, "'logout' not found in backend.api.auth.router"
    assert callable(fn)

def test_me_is_callable():
    """Function me exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.router")
    fn = getattr(mod, "me", None)
    assert fn is not None, "'me' not found in backend.api.auth.router"
    assert callable(fn)
