"""Smoke tests for backend/api/registry/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_registry_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    assert mod is not None

def test_slugify_is_callable():
    """Function slugify exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "slugify", None)
    assert fn is not None, "'slugify' not found in backend.api.registry.router"
    assert callable(fn)

def test_list_tools_is_callable():
    """Function list_tools exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "list_tools", None)
    assert fn is not None, "'list_tools' not found in backend.api.registry.router"
    assert callable(fn)

def test_get_tool_is_callable():
    """Function get_tool exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "get_tool", None)
    assert fn is not None, "'get_tool' not found in backend.api.registry.router"
    assert callable(fn)

def test_verify_repo_ownership_is_callable():
    """Function verify_repo_ownership exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "verify_repo_ownership", None)
    assert fn is not None, "'verify_repo_ownership' not found in backend.api.registry.router"
    assert callable(fn)

def test_submit_tool_is_callable():
    """Function submit_tool exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "submit_tool", None)
    assert fn is not None, "'submit_tool' not found in backend.api.registry.router"
    assert callable(fn)

def test_update_tool_is_callable():
    """Function update_tool exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "update_tool", None)
    assert fn is not None, "'update_tool' not found in backend.api.registry.router"
    assert callable(fn)

def test_deactivate_tool_is_callable():
    """Function deactivate_tool exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.registry.router")
    fn = getattr(mod, "deactivate_tool", None)
    assert fn is not None, "'deactivate_tool' not found in backend.api.registry.router"
    assert callable(fn)
