"""Smoke tests for backend/api/feed/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_feed_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.feed.router")
    assert mod is not None

def test_atom_feed_is_callable():
    """Function atom_feed exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.feed.router")
    fn = getattr(mod, "atom_feed", None)
    assert fn is not None, "'atom_feed' not found in backend.api.feed.router"
    assert callable(fn)
