"""Smoke tests for contracts/contracts_backend_api_auth_dependencies_interface/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_contracts_backend_api_auth_dependencies_interface_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_auth_dependencies_interface.interface")
    assert mod is not None

def test_get_current_user_is_callable():
    """Function get_current_user exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_auth_dependencies_interface.interface")
    fn = getattr(mod, "get_current_user", None)
    assert fn is not None, "'get_current_user' not found in contracts.contracts_backend_api_auth_dependencies_interface.interface"
    assert callable(fn)

def test_get_optional_user_is_callable():
    """Function get_optional_user exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_auth_dependencies_interface.interface")
    fn = getattr(mod, "get_optional_user", None)
    assert fn is not None, "'get_optional_user' not found in contracts.contracts_backend_api_auth_dependencies_interface.interface"
    assert callable(fn)
