"""Smoke tests for backend/api/search/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_search_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.search.router")
    assert mod is not None

def test_get_embedding_is_callable():
    """Function get_embedding exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.search.router")
    fn = getattr(mod, "get_embedding", None)
    assert fn is not None, "'get_embedding' not found in backend.api.search.router"
    assert callable(fn)

def test_search_tools_is_callable():
    """Function search_tools exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.search.router")
    fn = getattr(mod, "search_tools", None)
    assert fn is not None, "'search_tools' not found in backend.api.search.router"
    assert callable(fn)
