"""Smoke tests for backend/api/forum/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_forum_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    assert mod is not None

def test_list_categories_is_callable():
    """Function list_categories exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "list_categories", None)
    assert fn is not None, "'list_categories' not found in backend.api.forum.router"
    assert callable(fn)

def test_list_threads_is_callable():
    """Function list_threads exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "list_threads", None)
    assert fn is not None, "'list_threads' not found in backend.api.forum.router"
    assert callable(fn)

def test_get_thread_is_callable():
    """Function get_thread exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "get_thread", None)
    assert fn is not None, "'get_thread' not found in backend.api.forum.router"
    assert callable(fn)

def test_create_thread_is_callable():
    """Function create_thread exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "create_thread", None)
    assert fn is not None, "'create_thread' not found in backend.api.forum.router"
    assert callable(fn)

def test_create_reply_is_callable():
    """Function create_reply exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "create_reply", None)
    assert fn is not None, "'create_reply' not found in backend.api.forum.router"
    assert callable(fn)

def test_edit_reply_is_callable():
    """Function edit_reply exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "edit_reply", None)
    assert fn is not None, "'edit_reply' not found in backend.api.forum.router"
    assert callable(fn)

def test_delete_reply_is_callable():
    """Function delete_reply exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "delete_reply", None)
    assert fn is not None, "'delete_reply' not found in backend.api.forum.router"
    assert callable(fn)

def test_vote_thread_is_callable():
    """Function vote_thread exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "vote_thread", None)
    assert fn is not None, "'vote_thread' not found in backend.api.forum.router"
    assert callable(fn)

def test_unvote_thread_is_callable():
    """Function unvote_thread exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.forum.router")
    fn = getattr(mod, "unvote_thread", None)
    assert fn is not None, "'unvote_thread' not found in backend.api.forum.router"
    assert callable(fn)
