"""Smoke tests for backend/api/auth/dependencies.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_auth_dependencies():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.auth.dependencies")
    assert mod is not None

def test_get_current_user_is_callable():
    """Function get_current_user exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.dependencies")
    fn = getattr(mod, "get_current_user", None)
    assert fn is not None, "'get_current_user' not found in backend.api.auth.dependencies"
    assert callable(fn)

def test_get_optional_user_is_callable():
    """Function get_optional_user exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.auth.dependencies")
    fn = getattr(mod, "get_optional_user", None)
    assert fn is not None, "'get_optional_user' not found in backend.api.auth.dependencies"
    assert callable(fn)
