"""Smoke tests for contracts/backend_api_main/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_backend_api_main_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.backend_api_main.interface")
    assert mod is not None

def test_health_is_callable():
    """Function health exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.backend_api_main.interface")
    fn = getattr(mod, "health", None)
    assert fn is not None, "'health' not found in contracts.backend_api_main.interface"
    assert callable(fn)
