"""Smoke tests for backend/api/main.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_main():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.main")
    assert mod is not None

def test_health_is_callable():
    """Function health exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.main")
    fn = getattr(mod, "health", None)
    assert fn is not None, "'health' not found in backend.api.main"
    assert callable(fn)
