"""Smoke tests for backend/api/database.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_database():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.database")
    assert mod is not None

def test_get_db_is_callable():
    """Function get_db exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.database")
    fn = getattr(mod, "get_db", None)
    assert fn is not None, "'get_db' not found in backend.api.database"
    assert callable(fn)
