"""Smoke tests for backend/api/users/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_users_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    assert mod is not None

def test_get_user_profile_is_callable():
    """Function get_user_profile exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    fn = getattr(mod, "get_user_profile", None)
    assert fn is not None, "'get_user_profile' not found in backend.api.users.router"
    assert callable(fn)

def test_update_profile_is_callable():
    """Function update_profile exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    fn = getattr(mod, "update_profile", None)
    assert fn is not None, "'update_profile' not found in backend.api.users.router"
    assert callable(fn)

def test_download_my_data_is_callable():
    """Function download_my_data exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    fn = getattr(mod, "download_my_data", None)
    assert fn is not None, "'download_my_data' not found in backend.api.users.router"
    assert callable(fn)

def test_delete_account_is_callable():
    """Function delete_account exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    fn = getattr(mod, "delete_account", None)
    assert fn is not None, "'delete_account' not found in backend.api.users.router"
    assert callable(fn)

def test_get_starred_tools_is_callable():
    """Function get_starred_tools exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.users.router")
    fn = getattr(mod, "get_starred_tools", None)
    assert fn is not None, "'get_starred_tools' not found in backend.api.users.router"
    assert callable(fn)
