"""Smoke tests for contracts/contracts_backend_api_voting_router_interface/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_contracts_backend_api_voting_router_interface_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_voting_router_interface.interface")
    assert mod is not None

def test_vote_useful_is_callable():
    """Function vote_useful exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_voting_router_interface.interface")
    fn = getattr(mod, "vote_useful", None)
    assert fn is not None, "'vote_useful' not found in contracts.contracts_backend_api_voting_router_interface.interface"
    assert callable(fn)

def test_remove_vote_is_callable():
    """Function remove_vote exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_backend_api_voting_router_interface.interface")
    fn = getattr(mod, "remove_vote", None)
    assert fn is not None, "'remove_vote' not found in contracts.contracts_backend_api_voting_router_interface.interface"
    assert callable(fn)
