"""Smoke tests for backend/api/proximity/service.py (auto-generated by pact adopt)."""

import pytest

def test_import_backend_api_proximity_service():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("backend.api.proximity.service")
    assert mod is not None

def test_scan_proximity_is_callable():
    """Function scan_proximity exists and is callable."""
    import importlib
    mod = importlib.import_module("backend.api.proximity.service")
    fn = getattr(mod, "scan_proximity", None)
    assert fn is not None, "'scan_proximity' not found in backend.api.proximity.service"
    assert callable(fn)
